'''

MISM3405 Spring 2023
Benjamin Teixeira
    
Filename: MISM3045_citi.py
    
Description:
    question: how many citi bike riders ride daily
    that are subscribers vs. customers?
    
    answer: choose a single day of rides to examine
    dataset used generated by Citi Bike system data 
    found online
    
    program outline:
        read in datafile
        create variables to count
        for each row in file:
            if user type is subscriber add 1 to s count
            if customer, add 1 to c count
            otherwise, add 1 to o count
        print results
    
'''
# import libraries
import csv
import time

# open the csv
file = open("2009citi.csv", "r")

# pass file as ingredient to csv library's DictReader "recipe"
# store result in a variable called citi
citi = csv.DictReader(file)

# DictReader added useful info to data including
# fieldnames property letting us access all values in 
# first or "header" row
print(citi.fieldnames)

# create usertype counters
subscribers = 0
customers = 0
others = 0

# loop through data
for row in citi:
    
    # assign values to usertypes
    if row['usertype'] == "Subscriber":
        subscribers = subscribers + 1
    elif row['usertype'] == "Customer":
        customers = customers + 1
    else: 
        others = others + 1

# print values        
print(subscribers)
print(customers)
print(others)

# seeking scale
# when using a file with -text-text.csv in-between
# compare the two. time file
duration = time.process_time()
print(duration)




        
    